version: "3.8"

services:
    frontend:
      depends_on: 
        - backend
      build: ./frontend
      ports:
        - 80:80
    backend: 
      depends_on: 
        - db
        - redis
      build: ./backend
      ports: 
        - 3000:3000
      environment: 
        DB_URL: mongodb://db/users
      command: ./docker-entrypoint.sh
  
    db:
      image: mongo:4.0-xenial
      ports:
        - 27017:27017
    redis:
      image: redis:6.2-alpine
      ports:
        - 6379:6379
